name: main
on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 1 1,15 * *'
jobs:
  build:

    runs-on: windows-2019
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2
      - run: |
          ./syncMSServiceTags.ps1   
