id: 229f71ba-d83b-42a5-b83b-11a641049ed1
name: Cross-tenant Access Settings Organization Outbound Collaboration Settings Changed
description: |
  'Organizations are added in the Cross-tenant Access Settings to control communication inbound or outbound for users and applications. This detection notifies when Organization Outbound Collaboration Settings are changed for "Users & Groups" and for "Applications".'
severity: Medium
requiredDataConnectors:
  - connectorId: AzureActiveDirectory
    dataTypes:
      - AuditLogs
queryFrequency: 2d
queryPeriod: 2d
triggerOperator: gt
triggerThreshold: 0
status: Available
tactics:
  - InitialAccess
  - Persistence
  - Discovery
relevantTechniques:
  - T1078.004
  - T1136.003
  - T1087.004
query: |
  //In User & Groups and in Applications, the following "AccessType" values in columns PremodifiedOutboundSettings and ModifiedOutboundSettings are interpreted accordingly:
  // When Access Type in premodified outbound settings value was 1 that means that the initial access was allowed. When Access Type in premodified outbound settings value was 2 that means that the initial access was blocked. 
  // When Access Type in modified outbound settings value is 1 that means that now access is allowed. When Access Type in modified outbound settings value is 2 that means that now access is blocked. 
  AuditLogs
  | where OperationName has "Update a partner cross-tenant access setting"
  | where B2BType = TargetResources[0].modifiedProperties[0].displayName has "b2bCollaborationOutbound"
  | extend InitiatedByActionUserInformation = iff(isnotempty(InitiatedBy.user.userPrincipalName), InitiatedBy.user.userPrincipalName, InitiatedBy.app.displayName)
  | extend InitiatedByIPAdress = InitiatedBy.user.ipAddress
  | mv-expand PremodifiedOutboundSettings = TargetResources[0].modifiedProperties[0].oldValue to typeof(string)
  | mv-expand ModifiedOutboundSettings = TargetResources[0].modifiedProperties[0].newValue to typeof(string)
  | where PremodifiedOutboundSettings != ModifiedOutboundSettings
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: Name
        columnName: InitiatedByActionUserInformation
  - entityType: IP
    fieldMappings:
      - identifier: Address
        columnName: InitiatedByIPAdress
version: 1.0.0
kind: Scheduled
