id: f7f4a77e-f68f-4b56-9aaf-a0c9d87d7a8e
name: Network searching for Grey Noise Ips by CVE activity
description: |
  This query monitors network logs for matches of GreyNoise IPs discovered daily related to CVEs you are tracking in your enterprise or by MDE TVMs CVEs found on devices and servers.
severity: Low
requiredDataConnectors: []
queryFrequency: 1d
queryPeriod: 1d
triggerOperator: gt
triggerThreshold: 0
tactics:
  - Reconnaissance
  - Initial Access
relevantTechniques:
  - T1595
  - T1190
  - T1203
query: |
  let watchlist = (_GetWatchlist('GreyNoiseIPsbyCVEs') | project SearchKey);
  _ASim_NetworkSession
  | where SrcIpAddr in (watchlist) or DstIpAddr in (watchlist)
  | where SrcBytes >= 1 or DstBytes >= 1
  | project EventProduct, TimeGenerated, DvcHostname, SrcAppName, NetworkDirection, NetworkProtocol, SrcIpAddr, SrcPortNumber, SrcBytes, DstIpAddr, DstPortNumber, DstBytes, _ResourceId, SrcDvcId, NetworkSessionId, DstFQDN, DstGeoCountry, DstGeoRegion, DstGeoCity

entityMappings:
  - entityType: IP
    fieldMappings:
      - identifier: Address
        columnName: SrcIpAddr
  - entityType: IP
    fieldMappings:
      - identifier: Address
        columnName: DstIpAddr

version: 1.1.2
kind: Scheduled
metadata:
  source:
    kind: Community
  author:
    name: Nathan Swift
  support:
    tier: Community
  categories:
    domains: ["Security - Others"]
